spring.application.name=Library 2026

spring.datasource.url=jdbc:mysql://localhost:3306/library2026
spring.datasource.username=root
spring.datasource.password=PranavmySQL@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect